#!/bin/bash
# Updates the person name test data from CLDR

# The location of the `ex_cldr_person_names` repo
export EX_CLDR_PERSON_NAMES="${EX_CLDR_PERSON_NAMES:=$HOME/Development/cldr_person_names}"
[ ! -d $EX_CLDR_PERSON_NAMES ] && { echo "ex_cldr_person_names repository $EX_CLDR_UNIT was not found."; exit 1; }

# The location of the cloned CLDR repo
export CLDR_REPO="${CLDR_REPO:=$HOME/Development/cldr_repo}"
[ ! -d $CLDR_REPO ] && { echo "Unicode CLDR repository $CLDR_REPO was not found."; exit 1; }

cp -R $CLDR_REPO/common/testData/personNameTest $EX_CLDR_PERSON_NAMES/test/support/data/person_name_test_data